pool:
  vmImage: 'ubuntu-latest'  # Or your preferred agent with AzureRM tools

stages:
- stage: CreateVNET
  jobs:
  - job: CreateVNETJob
    steps:
    - script: |
        # Login to Azure using Azure Service Principal
        az login --service-principal -u "luca.tinelli@seznam.cz" -p "Mju76yhnbgt54rfv"

        # Set Azure subscription
        az account set --subscription "Marco_subscription"

        # Create the Virtual Network
        az network vnet create --name "Vnet_da_pipeline" --address-prefix "10.0.0.0/16" --resource-group "RG6"
      displayName: 'Create VNET'
